version: '3.8'

services:
  db:
    image: postgres:16
    container_name: items-db
    environment:
      POSTGRES_DB: itemsdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - items-net

  app:
    build: .
    container_name: items-api
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/itemsdb
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
    networks:
      - items-net

volumes:
  pgdata:

networks:
  items-net:
